FROM mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
ENV AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
ENV AZURE_COSMOS_EMULATOR_KEY="C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
ENV SERVICE_NAME="cosmos-emulator-svc"
ENV DATABASE_NAME="db1"
ENV CONTAINER_NAME="test"
# ENV AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE="0.0.0.0"

EXPOSE 8081 10250-10255
