FROM mcr.microsoft.com/azure-storage/azurite

ENV AZURITE_ACCOUNTS="cdbschema-azurite:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
ENV AZURITE_LOCATION="/cdbschema-azurite"
ENV AZURITE_ENABLE_ACCESS_LOG=true
ENV AZURITE_ENABLE_DEBUG_LOG=false
ENV AZURITE_SSL=false
ENV AZURITE_BLOB_PORT=10000
ENV AZURITE_QUEUE_PORT=10001
ENV AZURITE_TABLE_PORT=10002

RUN mkdir -p /data && chmod -R 777 /data

EXPOSE 10000-10002
